name: Audit web perf

on:
  push:
   branches: master
  schedule:
    - cron: '0 12 * * 3'

jobs:
  run_audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Use node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache Node.js modules
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.OS }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-yarn-

      - name: Install dependencies
        run: yarn install

      - name: Run web perf test job
        run: yarn run job:webtest
        env:
          PSI_API_KEY: ${{ secrets.PSI_API_KEY }}
          LIGHTHOUSE_API_KEY: ${{ secrets.LIGHTHOUSE_API_KEY }}
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}

      - name: Prepare files for reporting
        run: |
          cat > reports/LAST_UPDATED
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > reports/LAST_UPDATED
          # echo "Deleting unused files..."
          # rm -rf src
          # rm -rf .github
          # rm .eslintrc.js
          # rm .prettierrc.js
          # rm package-lock.json
          # rm package.json
          # rm tsconfig.json
          # rm yarn.lock

      - name: Commit files report
        run: |
          git config --local user.email "mazipanneh@gmail.com"
          git config --local user.name "mazipan"
          git add -A
          git commit -m "👋 Generated report 🚀"

      - name: GitHub Push
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          directory: ./reports
          force: true

      - name: Deploy to foo-bar.surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'webperf-ecommerce-id.surge.sh'
          project: './dist'
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}
