name: Audit web perf

on:
  push:
    branches:
      - master

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
        env:
          LIGHTHOUSE_API_KEY: ${{ secrets.LIGHTHOUSE_API_KEY }}
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
      - name: Run job
        run: |
          npm install
          npm run job:webtest
