name: Audit web perf

on:
  push:
    branches:
      - master

# on:
#  schedule:
#  - cron: "0 14 * * 2"

jobs:
  audit:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Cache Node.js modules
        uses: actions/cache@v1
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Install dependencies
        run: npm install

      - name: Run web perf test job
        run: npm run job:webtest
        # run: npm run test:gist
        env:
          LIGHTHOUSE_API_KEY: ${{ secrets.LIGHTHOUSE_API_KEY }}
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}

			- name: Commit files report
				run: |
					git config --local user.email "action@github.com"
					git config --local user.name "GitHub Action"
					git commit -m "Generate new report" -a

			- name: GitHub Push
  			uses: ad-m/github-push-action@v0.5.0
				with:
					directory: ./reports
					github_token: ${{ secrets.GIT_TOKEN }}

